#!/usr/bin/env fish

argparse p/path= -- $argv
or return 1

if not set -ql _flag_path
    echo "Error: path expected" >&2
    return 1
end
set path "$_flag_path"

if not test -d "$path"
    echo "Error: '$path' is not a directory" >&2
    return 1
end


set result (find "$path" -type f -exec sha256sum {} + | sort | uniq -dw64)

if test -z "$result"
    echo "No duplicates found"
    return
end

printf "%s\n" $result
