#!/bin/env bash

filename="$1"
contents="$(<$filename)"
no_quoted="$(echo "$contents" | perl -pe "s/\".*\"/\"\"/g")"
# also could've used sed, but perlre  is more extensive
# filter out contents from quotes since they're just strings

echo "$no_quoted" | grep -oP '(?!\d\w*)\w+' | xargs
# negative lookahead since \w includes digits and the first char can't be one
